SELECT
  OBSINT.DEBRIEFED_SPCOMP.SPECIES as species,
  CASE
    WHEN OBSINT.DEBRIEFED_LENGTH.GEAR in (1,2,3,4) THEN 1
    WHEN OBSINT.DEBRIEFED_LENGTH.GEAR in 6 THEN 2
    WHEN OBSINT.DEBRIEFED_LENGTH.GEAR in (5,7,9,10,11,68,8) THEN 3
  END AS gear,
  CONCAT('H',TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_JOIN)) AS haul_join,
  TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') AS month,
  CASE
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') <= 2 THEN 1
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') > 2
      AND TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') <= 4 THEN 2
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') > 4
      AND TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') <= 8 THEN 3
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') > 8
      AND TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') <= 10 THEN 4
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') > 10 THEN 5
  END AS season,
  CASE
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') in (1,2,3) THEN 1
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') in (4,5,6) THEN 2
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') in (7,8,9) THEN 3
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') in (10,11,12) THEN 4
  END AS quarter,
  CASE
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') in (1,2,3,4) THEN 1
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') in (5,6,7,8) THEN 2
    WHEN TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'MM') in (9,10,11,12) THEN 3
  END AS trimester,
  TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE, 'YYYY') AS year,
  OBSINT.DEBRIEFED_SPCOMP.EXTRAPOLATED_NUMBER AS numb,
  OBSINT.DEBRIEFED_SPCOMP.CRUISE AS cruise,
  OBSINT.DEBRIEFED_SPCOMP.PERMIT AS permit,
  OBSINT.DEBRIEFED_SPCOMP.HAUL AS haul,
  OBSINT.DEBRIEFED_SPCOMP.EXTRAPOLATED_WEIGHT / 1000 AS weight,
  OBSINT.DEBRIEFED_LENGTH.LENGTH AS length,
  OBSINT.DEBRIEFED_LENGTH.FREQUENCY AS frequency,
  OBSINT.DEBRIEFED_HAUL.LONDD_END AS lon,
  OBSINT.DEBRIEFED_HAUL.LATDD_END AS lat,
  OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE AS haul_date,
  OBSINT.DEBRIEFED_HAUL.NMFS_AREA AS area
FROM OBSINT.DEBRIEFED_HAUL
  INNER JOIN OBSINT.DEBRIEFED_SPCOMP
    ON OBSINT.DEBRIEFED_HAUL.HAUL_JOIN = OBSINT.DEBRIEFED_SPCOMP.HAUL_JOIN
  INNER JOIN OBSINT.DEBRIEFED_LENGTH
    ON OBSINT.DEBRIEFED_HAUL.HAUL_JOIN = OBSINT.DEBRIEFED_LENGTH.HAUL_JOIN
WHERE 
  OBSINT.DEBRIEFED_HAUL.NMFS_AREA BETWEEN 600 AND 699
  AND OBSINT.DEBRIEFED_LENGTH.NMFS_AREA != 670
  AND OBSINT.DEBRIEFED_SPCOMP.SPECIES
  -- insert species
  AND OBSINT.DEBRIEFED_LENGTH.SPECIES
  -- insert species

