SELECT
  NORPAC.DEBRIEFED_SPCOMP_MV.SPECIES AS species,
  NORPAC.DEBRIEFED_LENGTH_MV.GEAR AS gear,
  NORPAC.DEBRIEFED_SPCOMP_MV.CRUISE AS cruise,
  NORPAC.DEBRIEFED_SPCOMP_MV.PERMIT AS permit,
  NORPAC.DEBRIEFED_SPCOMP_MV.HAUL AS haul,
  CONCAT('H',TO_CHAR(NORPAC.DEBRIEFED_SPCOMP_MV.HAUL_JOIN)) AS haul_join,
  NORPAC.DEBRIEFED_HAUL_MV.LONDD_END AS lon,
  NORPAC.DEBRIEFED_HAUL_MV.LATDD_END AS lat,
  NORPAC.DEBRIEFED_SPCOMP_MV.HAUL_DATE AS haul_date,
  NORPAC.DEBRIEFED_HAUL_MV.NMFS_AREA AS area,
  NORPAC.DEBRIEFED_SPCOMP_MV.EXTRAPOLATED_NUMBER AS numb,
  NORPAC.DEBRIEFED_SPCOMP_MV.EXTRAPOLATED_WEIGHT / 1000 AS weight,
  NORPAC.DEBRIEFED_LENGTH_MV.LENGTH AS length,
  NORPAC.DEBRIEFED_LENGTH_MV.FREQUENCY AS frequency
FROM NORPAC.DEBRIEFED_HAUL_MV
  INNER JOIN NORPAC.DEBRIEFED_SPCOMP_MV
    ON NORPAC.DEBRIEFED_HAUL_MV.HAUL_JOIN = NORPAC.DEBRIEFED_SPCOMP_MV.HAUL_JOIN
  INNER JOIN NORPAC.DEBRIEFED_LENGTH_MV
    ON NORPAC.DEBRIEFED_HAUL_MV.HAUL_JOIN = NORPAC.DEBRIEFED_LENGTH_MV.HAUL_JOIN
WHERE 
  NORPAC.DEBRIEFED_HAUL_MV.NMFS_AREA BETWEEN 600 AND 699
  AND NORPAC.DEBRIEFED_LENGTH_MV.NMFS_AREA != 670
  AND NORPAC.DEBRIEFED_SPCOMP_MV.SPECIES
  -- insert species
  AND NORPAC.DEBRIEFED_LENGTH_MV.SPECIES
  -- insert species

