SELECT
  OBSINT.DEBRIEFED_SPCOMP.SPECIES AS species,
  OBSINT.DEBRIEFED_LENGTH.GEAR AS gear,
  OBSINT.DEBRIEFED_SPCOMP.CRUISE AS cruise,
  OBSINT.DEBRIEFED_SPCOMP.PERMIT AS permit,
  OBSINT.DEBRIEFED_SPCOMP.HAUL AS haul,
  CONCAT('H',TO_CHAR(OBSINT.DEBRIEFED_SPCOMP.HAUL_JOIN)) AS haul_join,
  OBSINT.DEBRIEFED_HAUL.LONDD_END AS lon,
  OBSINT.DEBRIEFED_HAUL.LATDD_END AS lat,
  OBSINT.DEBRIEFED_SPCOMP.HAUL_DATE AS haul_date,
  OBSINT.DEBRIEFED_HAUL.NMFS_AREA AS area,
  OBSINT.DEBRIEFED_SPCOMP.EXTRAPOLATED_NUMBER AS numb,
  OBSINT.DEBRIEFED_SPCOMP.EXTRAPOLATED_WEIGHT / 1000 AS weight,
  OBSINT.DEBRIEFED_LENGTH.LENGTH AS length,
  OBSINT.DEBRIEFED_LENGTH.FREQUENCY AS frequency
FROM OBSINT.DEBRIEFED_HAUL
  INNER JOIN OBSINT.DEBRIEFED_SPCOMP
    ON OBSINT.DEBRIEFED_HAUL.HAUL_JOIN = OBSINT.DEBRIEFED_SPCOMP.HAUL_JOIN
  INNER JOIN OBSINT.DEBRIEFED_LENGTH
    ON OBSINT.DEBRIEFED_HAUL.HAUL_JOIN = OBSINT.DEBRIEFED_LENGTH.HAUL_JOIN
WHERE 
  OBSINT.DEBRIEFED_HAUL.NMFS_AREA BETWEEN 600 AND 699
  AND OBSINT.DEBRIEFED_LENGTH.NMFS_AREA != 670
  AND OBSINT.DEBRIEFED_SPCOMP.SPECIES
  -- insert species
  AND OBSINT.DEBRIEFED_LENGTH.SPECIES
  -- insert species

